export interface DummyStudent {
    id: number,
    name: string,
    surname: string,
    pesel: string,
    email: string,
    country: string,
    city: string,
    street: string,
    home_num: string,
    flat_num: string | null,
    class: string
}

export const DUMMY_STUDENTS: DummyStudent[] = [
    {
        id: 1,
        name: "John",
        surname: "Smith",
        pesel: "12345678901",
        email: "JSmith@example.com",
        country: "USA",
        city: "New York",
        street: "Broadway",
        home_num: "123",
        flat_num: null,
        class: "5C"
    },
    {
        id: 2,
        name: "Emily",
        surname: "Johnson",
        pesel: "23456789012",
        email: "EJohnson@example.com",
        country: "USA",
        city: "Los Angeles",
        street: "Sunset Blvd",
        home_num: "456",
        flat_num: null,
        class: "4B"
    },
    {
        id: 3,
        name: "Michael",
        surname: "Brown",
        pesel: "34567890123",
        email: "MBrown@example.com",
        country: "USA",
        city: "Chicago",
        street: "Lake Shore Dr",
        home_num: "789",
        flat_num: null,
        class: "3A"
    },
    {
        id: 4,
        name: "Sarah",
        surname: "Davis",
        pesel: "45678901234",
        email: "SDavis@example.com",
        country: "USA",
        city: "Houston",
        street: "Main St",
        home_num: "1011",
        flat_num: null,
        class: "2B"
    },
    {
        id: 5,
        name: "David",
        surname: "Martinez",
        pesel: "56789012345",
        email: "DMartinez@example.com",
        country: "USA",
        city: "San Francisco",
        street: "Market St",
        home_num: "1213",
        flat_num: null,
        class: "1A"
    },
    {
        id: 6,
        name: "Jennifer",
        surname: "Anderson",
        pesel: "67890123456",
        email: "JAnderson@example.com",
        country: "USA",
        city: "Miami",
        street: "Ocean Dr",
        home_num: "1415",
        flat_num: null,
        class: "6C"
    },
    {
        id: 7,
        name: "Robert",
        surname: "Wilson",
        pesel: "78901234567",
        email: "RWilson@example.com",
        country: "USA",
        city: "Seattle",
        street: "Pike Pl",
        home_num: "1617",
        flat_num: null,
        class: "5A"
    },
    {
        id: 8,
        name: "Jessica",
        surname: "Taylor",
        pesel: "89012345678",
        email: "JTaylor@example.com",
        country: "USA",
        city: "Boston",
        street: "Newbury St",
        home_num: "1819",
        flat_num: null,
        class: "4D"
    },
    {
        id: 9,
        name: "Kevin",
        surname: "Thompson",
        pesel: "90123456789",
        email: "KThompson@example.com",
        country: "USA",
        city: "Dallas",
        street: "Elm St",
        home_num: "2021",
        flat_num: null,
        class: "3B"
    },
    {
        id: 10,
        name: "Laura",
        surname: "Garcia",
        pesel: "01234567890",
        email: "LGarcia@example.com",
        country: "USA",
        city: "Philadelphia",
        street: "Market St",
        home_num: "2223",
        flat_num: null,
        class: "2C"
    },
    {
        id: 11,
        name: "Andrew",
        surname: "Hernandez",
        pesel: "11234567890",
        email: "AHernandez@example.com",
        country: "USA",
        city: "Phoenix",
        street: "Camelback Rd",
        home_num: "2425",
        flat_num: null,
        class: "1B"
    },
    {
        id: 12,
        name: "Michelle",
        surname: "Young",
        pesel: "21234567890",
        email: "MYoung@example.com",
        country: "USA",
        city: "Denver",
        street: "Colfax Ave",
        home_num: "2627",
        flat_num: null,
        class: "6A"
    },
    {
        id: 13,
        name: "James",
        surname: "Lee",
        pesel: "31234567890",
        email: "JLee@example.com",
        country: "USA",
        city: "Las Vegas",
        street: "Las Vegas Blvd",
        home_num: "2829",
        flat_num: null,
        class: "5B"
    },
    {
        id: 14,
        name: "Sophia",
        surname: "Kim",
        pesel: "41234567890",
        email: "SKim@example.com",
        country: "USA",
        city: "Atlanta",
        street: "Peachtree St",
        home_num: "3031",
        flat_num: null,
        class: "4C"
    },
    {
        id: 15,
        name: "Daniel",
        surname: "Nguyen",
        pesel: "51234567890",
        email: "DNguyen@example.com",
        country: "USA",
        city: "Austin",
        street: "Congress Ave",
        home_num: "3233",
        flat_num: null,
        class: "3D"
    }
];