export interface User {
    id: number,
    role: string,
    email: string
}

export interface UserData {
    firstName: string | null,
    lastName: string | null,
    pesel: string | null,
    country: string | null,
    city: string | null,
    street: string | null,
    home_num: string | null,
    flat_num: string | null,
}

export const defaultUserData: UserData = {
    firstName: null,
    lastName: null,
    pesel: null,
    country: null,
    city: null,
    street: null,
    home_num: null,
    flat_num: null
};

type FullUser = User & UserData & {class: string | null};

export const DUMMY_STUDENTS: FullUser[] = [
    {
        id: 1,
        role: "Student",
        firstName: "John",
        lastName: "Smith",
        pesel: "12345678901",
        email: "JSmith@example.com",
        country: "USA",
        city: "New York",
        street: "Broadway",
        home_num: "123",
        flat_num: null,
        class: "5C"
    },
    {
        id: 2,
        role: "Student",
        firstName: "Emily",
        lastName: "Johnson",
        pesel: "23456789012",
        email: "EJohnson@example.com",
        country: "USA",
        city: "Los Angeles",
        street: "Sunset Blvd",
        home_num: "456",
        flat_num: null,
        class: "4B"
    },
    {
        id: 3,
        role: "Student",
        firstName: "Michael",
        lastName: "Brown",
        pesel: "34567890123",
        email: "MBrown@example.com",
        country: "USA",
        city: "Chicago",
        street: "Lake Shore Dr",
        home_num: "789",
        flat_num: null,
        class: "3A"
    },
    {
        id: 4,
        role: "Student",
        firstName: "Sarah",
        lastName: "Davis",
        pesel: "45678901234",
        email: "SDavis@example.com",
        country: "USA",
        city: "Houston",
        street: "Main St",
        home_num: "1011",
        flat_num: null,
        class: "2B"
    },
    {
        id: 5,
        role: "Student",
        firstName: "David",
        lastName: "Martinez",
        pesel: "56789012345",
        email: "DMartinez@example.com",
        country: "USA",
        city: "San Francisco",
        street: "Market St",
        home_num: "1213",
        flat_num: null,
        class: "1A"
    },
    {
        id: 6,
        role: "Student",
        firstName: "Jennifer",
        lastName: "Anderson",
        pesel: "67890123456",
        email: "JAnderson@example.com",
        country: "USA",
        city: "Miami",
        street: "Ocean Dr",
        home_num: "1415",
        flat_num: null,
        class: "6C"
    },
    {
        id: 7,
        role: "Student",
        firstName: "Robert",
        lastName: "Wilson",
        pesel: "78901234567",
        email: "RWilson@example.com",
        country: "USA",
        city: "Seattle",
        street: "Pike Pl",
        home_num: "1617",
        flat_num: null,
        class: "5A"
    },
    {
        id: 8,
        role: "Student",
        firstName: "Jessica",
        lastName: "Taylor",
        pesel: "89012345678",
        email: "JTaylor@example.com",
        country: "USA",
        city: "Boston",
        street: "Newbury St",
        home_num: "1819",
        flat_num: null,
        class: "4D"
    },
    {
        id: 9,
        role: "Student",
        firstName: "Kevin",
        lastName: "Thompson",
        pesel: "90123456789",
        email: "KThompson@example.com",
        country: "USA",
        city: "Dallas",
        street: "Elm St",
        home_num: "2021",
        flat_num: null,
        class: "3B"
    },
    {
        id: 10,
        role: "Student",
        firstName: "Laura",
        lastName: "Garcia",
        pesel: "01234567890",
        email: "LGarcia@example.com",
        country: "USA",
        city: "Philadelphia",
        street: "Market St",
        home_num: "2223",
        flat_num: null,
        class: "2C"
    },
    {
        id: 11,
        role: "Student",
        firstName: "Andrew",
        lastName: "Hernandez",
        pesel: "11234567890",
        email: "AHernandez@example.com",
        country: "USA",
        city: "Phoenix",
        street: "Camelback Rd",
        home_num: "2425",
        flat_num: null,
        class: "1B"
    },
    {
        id: 12,
        role: "Student",
        firstName: "Michelle",
        lastName: "Young",
        pesel: "21234567890",
        email: "MYoung@example.com",
        country: "USA",
        city: "Denver",
        street: "Colfax Ave",
        home_num: "2627",
        flat_num: null,
        class: "6A"
    },
    {
        id: 13,
        role: "Student",
        firstName: "James",
        lastName: "Lee",
        pesel: "31234567890",
        email: "JLee@example.com",
        country: "USA",
        city: "Las Vegas",
        street: "Las Vegas Blvd",
        home_num: "2829",
        flat_num: null,
        class: "5B"
    },
    {
        id: 14,
        role: "Student",
        firstName: "Sophia",
        lastName: "Kim",
        pesel: "41234567890",
        email: "SKim@example.com",
        country: "USA",
        city: "Atlanta",
        street: "Peachtree St",
        home_num: "3031",
        flat_num: null,
        class: "4C"
    },
    {
        id: 15,
        role: "Student",
        firstName: "Daniel",
        lastName: "Nguyen",
        pesel: "51234567890",
        email: "DNguyen@example.com",
        country: "USA",
        city: "Austin",
        street: "Congress Ave",
        home_num: "3233",
        flat_num: null,
        class: "3D"
    }
];